# This file was generated by GoReleaser. DO NOT EDIT.
cask "ofga" do
  version "0.267.0"

  on_macos do
    on_intel do
      sha256 "4e750d01c174fbbab08d068bcab38e5a8c94eb6f70c3e55a8edaece7975550ca"
      url "https://github.com/sergiught/openfga-cli/releases/download/v0.267.0/ofga_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7ce2004d4a1b191779d76830fa397f4a28c9f7d50ca925d4e635cd4e253cc8c0"
      url "https://github.com/sergiught/openfga-cli/releases/download/v0.267.0/ofga_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "167f6998b07edcae373893eefcb295e461e6bfaec348e27927d8f755c168fc2f"
      url "https://github.com/sergiught/openfga-cli/releases/download/v0.267.0/ofga_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ecaa83cf1aac263cffdcc5a244171cf3e4e71cddcc567aac66ba653713834b2c"
      url "https://github.com/sergiught/openfga-cli/releases/download/v0.267.0/ofga_Linux_arm64.tar.gz"
    end
  end

  name "ofga"
  desc "A modern CLI & TUI for OpenFGA."
  homepage "https://github.com/sergiught/openfga-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ofga"
  manpage "man/ofga-api.1"
  manpage "man/ofga-assertions-read.1"
  manpage "man/ofga-assertions-test.1"
  manpage "man/ofga-assertions-write.1"
  manpage "man/ofga-assertions.1"
  manpage "man/ofga-completion-bash.1"
  manpage "man/ofga-completion-fish.1"
  manpage "man/ofga-completion-powershell.1"
  manpage "man/ofga-completion-zsh.1"
  manpage "man/ofga-completion.1"
  manpage "man/ofga-config-path.1"
  manpage "man/ofga-config.1"
  manpage "man/ofga-init.1"
  manpage "man/ofga-model-get.1"
  manpage "man/ofga-model-graph.1"
  manpage "man/ofga-model-latest.1"
  manpage "man/ofga-model-list.1"
  manpage "man/ofga-model-test-init.1"
  manpage "man/ofga-model-test-schema.1"
  manpage "man/ofga-model-test.1"
  manpage "man/ofga-model-write.1"
  manpage "man/ofga-model.1"
  manpage "man/ofga-playground.1"
  manpage "man/ofga-profiles-add.1"
  manpage "man/ofga-profiles-cleanup-credentials.1"
  manpage "man/ofga-profiles-current.1"
  manpage "man/ofga-profiles-list.1"
  manpage "man/ofga-profiles-remove.1"
  manpage "man/ofga-profiles-set.1"
  manpage "man/ofga-profiles-show.1"
  manpage "man/ofga-profiles-unset.1"
  manpage "man/ofga-profiles-use.1"
  manpage "man/ofga-profiles.1"
  manpage "man/ofga-query-batch-check.1"
  manpage "man/ofga-query-check.1"
  manpage "man/ofga-query-expand.1"
  manpage "man/ofga-query-list-objects.1"
  manpage "man/ofga-query-list-relations.1"
  manpage "man/ofga-query-list-users.1"
  manpage "man/ofga-query.1"
  manpage "man/ofga-stores-create.1"
  manpage "man/ofga-stores-delete.1"
  manpage "man/ofga-stores-get.1"
  manpage "man/ofga-stores-list.1"
  manpage "man/ofga-stores.1"
  manpage "man/ofga-theme.1"
  manpage "man/ofga-tuples-changes.1"
  manpage "man/ofga-tuples-delete.1"
  manpage "man/ofga-tuples-read.1"
  manpage "man/ofga-tuples-write.1"
  manpage "man/ofga-tuples.1"
  manpage "man/ofga-version.1"
  manpage "man/ofga.1"
  bash_completion "completions/ofga.bash"
  fish_completion "completions/ofga.fish"
  zsh_completion "completions/ofga.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ofga"]
    end
  end

  # No zap stanza required

end
