# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ofga < Formula
  desc "A modern CLI & TUI for OpenFGA."
  homepage "https://github.com/sergiught/openfga-cli"
  version "0.264.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sergiught/openfga-cli/releases/download/v0.264.0/ofga_Darwin_x86_64.tar.gz"
      sha256 "6fba7bf062801857ff64c4e983dd6e0dffa5eaf7fc90a170c4855675850e0c56"

      define_method(:install) do
        bin.install "ofga"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sergiught/openfga-cli/releases/download/v0.264.0/ofga_Darwin_arm64.tar.gz"
      sha256 "ad14971d1d29a44d58848ee108c7d5e9a8ea139060df0b155b2084d81a11e234"

      define_method(:install) do
        bin.install "ofga"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sergiught/openfga-cli/releases/download/v0.264.0/ofga_Linux_x86_64.tar.gz"
      sha256 "c80addd525063d37099a825145e8981a9179bd5729ecd73c0d3d0ad08c98c48a"
      define_method(:install) do
        bin.install "ofga"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sergiught/openfga-cli/releases/download/v0.264.0/ofga_Linux_arm64.tar.gz"
      sha256 "ad798d9ae7e3ce7f6c2f2a26cecf2aa94fc3c83ec58145c4737ab6f11c2415d1"
      define_method(:install) do
        bin.install "ofga"
      end
    end
  end

  test do
    system "#{bin}/ofga version"
  end
end
