# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ofga < Formula
  desc "A modern CLI & TUI for OpenFGA."
  homepage "https://github.com/sergiught/openfga-cli"
  version "0.263.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/sergiught/openfga-cli/releases/download/v0.263.1/ofga_Darwin_x86_64.tar.gz"
      sha256 "080abe73cb54caebea80aad480b56157ea02d63a3053050989d265c2f89f660c"

      def install
        bin.install "ofga"
      end
    end
    on_arm do
      url "https://github.com/sergiught/openfga-cli/releases/download/v0.263.1/ofga_Darwin_arm64.tar.gz"
      sha256 "5f1afded45635c15b743d4e79886a42704dbcb248b74196056dc143a9b538a77"

      def install
        bin.install "ofga"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sergiught/openfga-cli/releases/download/v0.263.1/ofga_Linux_x86_64.tar.gz"
        sha256 "22d22b957d0693d2099d32950f85953222bc360339dd886c6cae5596c541133d"

        def install
          bin.install "ofga"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sergiught/openfga-cli/releases/download/v0.263.1/ofga_Linux_arm64.tar.gz"
        sha256 "7cf2b02368fe0c123ed63d6a0fdfff5890d10cd72f29b2ff967e4643f342353a"

        def install
          bin.install "ofga"
        end
      end
    end
  end

  test do
    system "#{bin}/ofga version"
  end
end
