# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ofga < Formula
  desc "A modern CLI & TUI for OpenFGA."
  homepage "https://github.com/sergiught/openfga-cli"
  version "0.267.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sergiught/openfga-cli/releases/download/v0.267.0/ofga_Darwin_x86_64.tar.gz"
      sha256 "4e750d01c174fbbab08d068bcab38e5a8c94eb6f70c3e55a8edaece7975550ca"

      define_method(:install) do
        bin.install "ofga"
        bash_completion.install "completions/ofga.bash" => "ofga"
        zsh_completion.install "completions/ofga.zsh" => "_ofga"
        fish_completion.install "completions/ofga.fish"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sergiught/openfga-cli/releases/download/v0.267.0/ofga_Darwin_arm64.tar.gz"
      sha256 "7ce2004d4a1b191779d76830fa397f4a28c9f7d50ca925d4e635cd4e253cc8c0"

      define_method(:install) do
        bin.install "ofga"
        bash_completion.install "completions/ofga.bash" => "ofga"
        zsh_completion.install "completions/ofga.zsh" => "_ofga"
        fish_completion.install "completions/ofga.fish"
        man1.install Dir["man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sergiught/openfga-cli/releases/download/v0.267.0/ofga_Linux_x86_64.tar.gz"
      sha256 "167f6998b07edcae373893eefcb295e461e6bfaec348e27927d8f755c168fc2f"
      define_method(:install) do
        bin.install "ofga"
        bash_completion.install "completions/ofga.bash" => "ofga"
        zsh_completion.install "completions/ofga.zsh" => "_ofga"
        fish_completion.install "completions/ofga.fish"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sergiught/openfga-cli/releases/download/v0.267.0/ofga_Linux_arm64.tar.gz"
      sha256 "ecaa83cf1aac263cffdcc5a244171cf3e4e71cddcc567aac66ba653713834b2c"
      define_method(:install) do
        bin.install "ofga"
        bash_completion.install "completions/ofga.bash" => "ofga"
        zsh_completion.install "completions/ofga.zsh" => "_ofga"
        fish_completion.install "completions/ofga.fish"
        man1.install Dir["man/*.1"]
      end
    end
  end

  test do
    system "#{bin}/ofga version"
  end
end
